networks:
  main:
    driver: bridge

volumes:
  db_data:
    

services:

  database:
    image: postgres:15
    volumes:
      - ./docker/pgData:/var/lib/postgresql/data
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - main

  whyapp:
    depends_on:
      - database
    container_name: whyapp
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    ports:
      - "3000:3000"
    networks:
      - main