version: '3'

services:
  database:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=docker
    ports:
      - "5435:5432"
  whyapp:
    build: .
    depends_on:
      - database
    ports:
      - "3000:3000"